name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.ref_name }}
          path: .cache
      # Instala mkdocs y el tema material utilizado en tu mkdocs.yml
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
      # Configura credenciales de Git para el despliegue automático
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      # Despliega a la rama gh-pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
